#!/bin/bash

# Lorenzo Cocchi workaround temporaneo per join htaccess del SIA
# e quello degli utenti esterni in modo da segare LDAP su SVN

umask 0077
LANG=C
IFS=$' \t\n'

SIA_HTUSERS="/var/www/web31/sia/data/htusers"
EXT_HTUSERS="/var/www/web31/web/ws/tracusers.list"
TMP_EXT_HTUSERS="/tmp/ext_htusers"
TMP_HTUSERS="/tmp/htusers"

REMOTE_HOSTS="
cluster.tools.softecspa.it
ext-antibrote-nagios.cluster-antibrote.softecspa.it
"


die() {
    local MSG="$1"
    local E=${2-1}
    echo "${MSG}" >&2
    exit ${E}
}

EXT_USERS="$(sed -n '/BeginExt/,/EndExt/p' ${EXT_HTUSERS} | egrep -v '#')"

if [ $# -ne 0 ] || [ -z "${EXT_USERS}" ]; then
    die "can not select external users"
fi

echo "${EXT_USERS}" >${TMP_EXT_HTUSERS}
cat ${SIA_HTUSERS} ${TMP_EXT_HTUSERS} >${TMP_HTUSERS}

chmod 0440 ${TMP_HTUSERS}
chown www-data:root ${TMP_HTUSERS}

for RHOST in ${REMOTE_HOSTS}; do
    rsync -aq --min-size=1 -e \
        "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=20" \
        ${TMP_HTUSERS} ${RHOST}:/var/www/.htusers
done

if [ $# -ne 0 ]; then
    die "can not rsync ${TMP_HTUSERS}"
fi

rm ${TMP_EXT_HTUSERS} ${TMP_HTUSERS}

# EOF
